### ISSUE TITLE
set inspec_version: ">= 4.0"

### ISSUE THREAD

**Issue by ejaronne** [mitre/oracle-java-runtime-environment-8-unix-stig-baseline#6]
or inspec_version: ">= 3.0"

**Comment by Amndeep7** [comment]
https://github.com/mitre/oracle-java-runtime-environment-8-unix-stig-baseline/blob/faac211901648859db5dc729df292a3fe1f32020/inspec.yml#L9

seems to be implemented.  please reopen @ejaronne if something else needs to be done.
